In [2]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split


In [3]:
iris=load_iris()

In [4]:
print(iris['target_names'])

['setosa' 'versicolor' 'virginica']


In [5]:
print(iris['feature_names'])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
print(iris['data'].shape)

(150, 4)


In [7]:
print(iris['target'].shape)

(150,)


In [9]:
X_train,X_test,y_train,y_test=train_test_split(iris['data'],iris['target'],random_state=0)


In [10]:
print(X_train.shape,y_train.shape)

(112, 4) (112,)


In [11]:
print(X_test.shape,y_test.shape)

(38, 4) (38,)


Now, I'm building the K Nearest Neighbors Classifier model to predict the target type depending on the sepal and petal length and width.

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)


Now, the model is been loaded with the neighbors value set to 1 which mean that only the nearest neighbor influences the model's prediction. Now, in the next steps, I will fit the model on my training data, remember that the model is needed to be fit on the training data and predictions are needed to be done on the testing data. Let's see this in action!

In [13]:
knn.fit(X_train, y_train)


KNeighborsClassifier(n_neighbors=1)

Now, the model is fitted on the training data and now we can call predict method over the testing dataset.

In [14]:
y_pred=knn.predict(X_test)

In [15]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

In [16]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1])

remember that y_pred is our predictions made from the model knn and y_test are the true or original labels, now we need to compare them to get the accuracy of our model predictions

In [17]:
np.mean(y_pred==y_test)

0.9736842105263158

Well, we can use default method by scikit learn to get to know about the accuracy.

In [18]:
knn.score(X_test,y_test)

0.9736842105263158

Now, let's build another model with nearest neighbors as 3 


In [19]:
knn3=KNeighborsClassifier(n_neighbors=3)
knn3.fit(X_train,y_train)
y_pred3=knn3.predict(X_test)
print('The accuracy is ', np.mean(y_pred3==y_test))

The accuracy is  0.9736842105263158


In [20]:
y_pred3

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

There's not much difference in terms of improvement in accuracy.